
theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
# true-color = true
rulers = [80]
color-modes = true

[editor.statusline]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
characer = "|"

[keys.normal]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"

